# "service" is the name of this project. This will also be added to your AWS resource names.
service: dont-keep-working-so-hard-dad

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  profile: default
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - iot:Publish
            - iot:Subscribe
            - iot:Connect
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:Query
          Resource: { "Fn::GetAtt": ["SensorDataTable", "Arn"] }

resources:
  Resources:
    SensorDataRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - iot.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: SensorDataPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource: { "Fn::GetAtt": ["SensorDataTable", "Arn"] }

    SernsorThing:
      Type: AWS::IoT::Thing
      Properties:
        ThingName: dkwshd-sensor1

    SensorDataRule:
      Type: AWS::IoT::TopicRule
      Properties:
        RuleName: dkwshd_sensor_data_rule
        TopicRulePayload:
          Actions:
            - DynamoDBv2:
                RoleArn: { "Fn::GetAtt": ["SensorDataRole", "Arn"] }
                PutItem:
                  TableName: { "Fn::GetAtt": ["SensorDataTable", "Arn"] }
          AwsIotSqlVersion: "2016-03-23"
          Sql: "SELECT concat(topic(2),'-',parse_time(\"yyyy-MM-dd\",timestamp(), 'UTC')) AS partitionKey, unixTime, distance FROM 'devices/+/messages/events/#'"
          RuleDisabled: false

    SensorDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dkwshd-sensor-data
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: unixTime
            AttributeType: N
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: unixTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  rateHandler:
    handler: lambda-handler.run
    events:
      - schedule: cron(0/5 0-9 ? * MON-FRI *)
